OPENAI_API_KEY = "sk-2...X"

[connections.snowflake]
user = "LLM_USER"
password = "SYo2024"
warehouse = "WH_S"
role = "LLM_ROLE"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "pq84751"